# Generated by Django 4.0.4 on 2022-06-19 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('feab3d72-dc10-4484-b9f0-fdb64d29d196'), editable=False, primary_key=True, serialize=False),
        ),
    ]
