# Generated by Django 4.0.4 on 2022-06-19 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d2bc5ba7-57f2-4d3e-ae2c-d6a10607f981'), editable=False, primary_key=True, serialize=False),
        ),
    ]
